apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-churn-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-churn-app
  template:
    metadata:
      labels:
        app: customer-churn-app
    spec:
      containers:
      - name: app
        image: hana367/customer-churn-app:4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
