artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/hannamhiri/ecommerce_customer_churn_dataset/raw/main/archive%20(1).zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/ecommerce_customer_churn_dataset.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/ecommerce_customer_churn_dataset.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_dir: artifacts/model_trainer
  metric_file_name: artifacts/model_evaluation/metrics.json
